apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.0.7
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 11.0.11
name: django-app
version: 1.0.2
